spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:onedoller-shop
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  #        show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console